Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Exception: This is the error message.


/*
>>> import traceback
>>> try:
...     raise Exception("This is the error message.")
... except:
...     errorFile = open("errorInfo.txt", "w")
...     errorFile.write(traceback.format_exc())
...     errorFile.close()
...     print("The traceback info was written to errorInfo.txt")
...
111
The traceback info was written to errorInfo.txt
*/